---
title: "NHL"
author: "Todd Idol"
date: "9/8/2020"
output: 
   github_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, warning = FALSE, message = FALSE)
rmarkdown::find_pandoc(version = '2.10.1')
library(tidyverse)
library(tinytex)
library(jsonlite)
library(httr)
library(DT)
library(shiny)
library(rmarkdown)
```
```{r, render readme}
rmarkdown::render(input = "P1_TKIdol.Rmd", output_file = "README.md")
```
# [Prject Repo](https://github.com/tkidol/ST558-Project-1)

# NHL Franchises


```{r Franchise API}
# GET pull for NHL franchise
FranchiseAPI <- function() {
franchise <- GET("https://records.nhl.com/site/api/franchise")

## As JSON text
franchise <- content(franchise, "text")

## As JSON List
franchise <- fromJSON(franchise, flatten = TRUE)

franchise <- franchise[[1]] %>% rename("Franchise ID" = id, "First Season" = firstSeasonId, "Last Season" = lastSeasonId, "Team ID" = mostRecentTeamId, "Name" = teamCommonName, "Location" = teamPlaceName)
return(franchise)
}
```
```{r TeamTotal API}
# GET pull for NHL Team Totals
TeamTotalsAPI<- function() {
totals <- GET("https://records.nhl.com/site/api/franchise-team-totals")

## As JSON text
totals <- content(totals, "text")

## As JSON List
totals <- fromJSON(totals, flatten = TRUE)
return(totals[[1]])
}
```

```{r, Team DrillDown API}
TeamDDAPI <- function(id, ...) {
# GET pull for NHL Team Totals
drill_down <- GET(paste0("https://records.nhl.com/site/api/franchise-season-records?cayenneExp=franchiseId=", id))

## As JSON text
drill_down <- content(drill_down, "text")

## As JSON List
drill_down <- fromJSON(drill_down, flatten = TRUE)
return(drill_down[[1]])
}
```

```{r Goalie API}
GoalieAPI <- function(id, ...) {
# GET pull for NHL Team Totals
goalie <- GET(paste0("https://records.nhl.com/site/api/franchise-goalie-records?cayenneExp=franchiseId=", id))

## As JSON text
goalie <- content(goalie, "text")

## As JSON List
goalie <- fromJSON(goalie, flatten = TRUE)
return(goalie[[1]])
}
```

```{r, Skater API}
SkaterAPI <- function(id, ...) {
# GET pull for NHL Team Totals
skater <- GET(paste0("https://records.nhl.com/site/api/franchise-skater-records?cayenneExp=franchiseId=", id))

## As JSON text
skater <- content(skater, "text")

## As JSON List
skater <- fromJSON(skater, flatten = TRUE)
return(skater[[1]])
}
```

```{r, Test  Record API calls}
FranchiseAPI_Call <- arrange(FranchiseAPI(), desc("Team ID"))
knitr::kable(head(FranchiseAPI_Call))

TeamTotalsAPI_Call <- head(TeamTotalsAPI())
knitr::kable(TeamTotalsAPI_Call)

TeamDDAPI_Call <- head(TeamDDAPI(5))
knitr::kable(TeamDDAPI_Call)

GoalieAPI_Call <- head(GoalieAPI(1))
knitr::kable(GoalieAPI_Call)

SkaterAPI_Call <- head(SkaterAPI(1))
knitr::kable(SkaterAPI_Call)
```

```{r, Team Stats API}
TeamStatsAPI <- function() {
stats <- GET("https://statsapi.web.nhl.com/api/v1/teams")

## As JSON text
stats <- content(stats, "text")

## As JSON List
stats <- fromJSON(stats, flatten = TRUE)
return(stats[[2]])
}
```

```{r, Roster API}
RosterAPI <- function(id, ...) {
roster <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "/?expand=team.roster"))

## As JSON text
roster <- content(roster, "text")

## As JSON List
roster <- fromJSON(roster, flatten = TRUE)
franchiseId <- roster$teams$franchiseId
roster <- tbl_df(roster[[2]]$roster.roster[[1]]) %>% mutate("franchiseId" = franchiseId) %>% 
select(franchiseId, everything())
return(roster)
}
```

```{r, Person API}
PersonAPI <- function(id, ...) {
person <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "/?expand=person.names"))

## As JSON text
person <- content(person, "text")

## As JSON List
person <- fromJSON(person, flatten = TRUE)
return(person[[2]])
}
```

```{r, People API}
# Detailed substitue for PersonAPI
PeopleAPI <- function(id, ...) {
people <- GET(paste0("https://statsapi.web.nhl.com/api/v1/people/", id))

## As JSON text
people <- content(people, "text")

## As JSON List
people <- fromJSON(people, flatten = TRUE)
return(people[[2]])
}
```

```{r, team player}
## New DF combining People with Roster
TeamPlayer <- function (id, ...) {
playerId <- pull(RosterAPI(id), person.id)
players <- as.data.frame(PeopleAPI(playerId[1]))
  for (i in 2:length(playerId)) {
    players[i, ] <- (PeopleAPI(playerId[i]))
  }
players <- players %>% select(c(-26, -24, -23, -22, -21, -12, -10, -9,  -5, -4))
return(players) 
}
```
```{r, test team player}
TPtest <- TeamPlayer(12)
knitr::kable(head(TPtest))
```

```{r, Next Game API}
NextGAPI <- function(id, ...) {
nextG <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "?expand=team.schedule.next"))

## As JSON text
nextG <- content(nextG, "text")

## As JSON List
nextG <- fromJSON(nextG, flatten = TRUE)
nextG <- nextG[[2]]$nextGameSchedule.dates[[1]]$games[[1]]
return(nextG)
}
```

```{r, Prior Game API}
PriorGAPI <- function(id, ...) {
priorG <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "?expand=team.schedule.previous"))

## As JSON text
priorG <- content(priorG, "text")

## As JSON List
priorG <- fromJSON(priorG, flatten = TRUE)
priorG <- priorG[[2]]$previousGameSchedule.dates
return(priorG)
}
```


```{r, Expanded Stats API}
ExpStatsAPI <- function(id, ...) {
expStats <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "?expand=team.stats"))

## As JSON text
expStats <- content(expStats, "text")

## As JSON List
expStats <- fromJSON(expStats, flatten = TRUE)
expStats <- as.data.frame(expStats[[2]]$teamStats[[1]]$splits)
return(expStats)
}
```
```{r, exp stats test}
expstatstest <- ExpStatsAPI(12)
knitr::kable(tbl_df(expstatstest))
```


```{r, Season Stats API}
SeasonAPI <- function(id, season, ...) {
season <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "?expand=team.roster&season=", season))

## As JSON text
season <- content(season, "text")

## As JSON List
season <- fromJSON(season, flatten = TRUE)
franchiseId <- season$teams$franchiseId
season <- tbl_df((season[[2]]$roster.roster[[1]])) %>% mutate("franchiseId" = franchiseId) %>% select(franchiseId, everything())
return(season)
}
```

```{r, Multi Teams API}
MultiAPI <- function(id, ...) {
multi <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", "?teamId=", id))

## As JSON text
multi <- content(multi, "text")

## As JSON List
multi <- fromJSON(multi, flatten = TRUE)
return(multi[[2]])
}
```

```{r, Playoffs API}
PlayoffAPI <- function(id, ...) {
playoff <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "?stats=statsSingleSeasonPlayoffs"))

## As JSON text
playoff <- content(playoff, "text")

## As JSON List
playoff <- fromJSON(playoff, flatten = TRUE)
return(playoff[[2]])
}
```


```{r, Test Stats API calls}
TeamStatsAPI_Call <- head(TeamStatsAPI())
knitr::kable(TeamStatsAPI_Call)

RosterAPI_Call <- head(RosterAPI(10))
knitr::kable(RosterAPI_Call)

PersonAPI_Call <- head(PersonAPI(10))
knitr::kable(PersonAPI_Call)

PeopleAPI_Call <- head(PeopleAPI(8468508))
knitr::kable(PeopleAPI_Call)

NextGAPI_Call <- head(NextGAPI(1))
knitr::kable(NextGAPI_Call)

PriorGAPI_Call <- head(PriorGAPI(12))
knitr::kable(PriorGAPI_Call)

SeasonAPI_Call <- head(SeasonAPI(12, 20052006))
knitr::kable(SeasonAPI_Call)

MultiID_Call <- head(MultiAPI(paste0("1,2,3")))
knitr::kable(MultiID_Call)

PlayoffAPI_Call <- head(PlayoffAPI(3))
knitr::kable(PlayoffAPI_Call)
```

##{r, user input}
t_id <- FranchiseAPI()[ , "Team ID"] 
selectInput("n",label = "Choose a Team ID", choices = t_id, selected = 26)
renderDT({RosterAPI(input$n)})
```
