---
title: "NHL"
author: "Todd Idol"
date: "9/8/2020"
always_allow_html: true
output: 
   github_document:
    toc: true
    toc_depth: 3
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, warning = FALSE, message = FALSE)
rmarkdown::find_pandoc(version = '2.10.1')
options(knitr.duplicate.label = "allow")
library(tidyverse)
library(tinytex)
library(jsonlite)
library(httr)
library(DT)
library(rmarkdown)
library(knitr)
library(GGally)
```

# NHL Franchises

```{r, Franchise API}
# GET pull for NHL franchise
FranchiseAPI <- function() {
franchise <- GET("https://records.nhl.com/site/api/franchise")

## As JSON text
franchise <- content(franchise, "text")

## As JSON List
franchise <- fromJSON(franchise, flatten = TRUE)

franchise <- franchise[[1]] %>% rename("Franchise ID" = id, "First Season" = firstSeasonId, "Last Season" = lastSeasonId, "Team ID" = mostRecentTeamId, "Name" = teamCommonName, "Location" = teamPlaceName)
return(franchise)
}
```

```{r TeamTotal API}
# GET pull for NHL Team Totals
TeamTotalsAPI<- function() {
totals <- GET("https://records.nhl.com/site/api/franchise-team-totals")

## As JSON text
totals <- content(totals, "text")

## As JSON List
totals <- fromJSON(totals, flatten = TRUE)
return(totals[[1]])
}
```

```{r, Team DrillDown API}
TeamDDAPI <- function(id, ...) {
# GET pull for NHL Team Totals
drill_down <- GET(paste0("https://records.nhl.com/site/api/franchise-season-records?cayenneExp=franchiseId=", id))

## As JSON text
drill_down <- content(drill_down, "text")

## As JSON List
drill_down <- fromJSON(drill_down, flatten = TRUE)
return(drill_down[[1]])
}
```

```{r Goalie API}
GoalieAPI <- function(id, ...) {
# GET pull for NHL Team Totals
goalie <- GET(paste0("https://records.nhl.com/site/api/franchise-goalie-records?cayenneExp=franchiseId=", id))

## As JSON text
goalie <- content(goalie, "text")

## As JSON List
goalie <- fromJSON(goalie, flatten = TRUE)
return(goalie[[1]])
}
```

```{r, Skater API}
SkaterAPI <- function(id, ...) {
# GET pull for NHL Team Totals
skater <- GET(paste0("https://records.nhl.com/site/api/franchise-skater-records?cayenneExp=franchiseId=", id))

## As JSON text
skater <- content(skater, "text")

## As JSON List
skater <- fromJSON(skater, flatten = TRUE)
return(skater[[1]])
}
```

```{r, franchise call}
Franchise <- FranchiseAPI()
Franchise <- arrange(Franchise, (Franchise[[4]]))
kable((Franchise), caption = "Franchise All")
```

```{r, Record API calls}
SkaterAPI_Call <- head(SkaterAPI(1))
glimpse(SkaterAPI_Call)
```

```{r, Team Stats API}
TeamStatsAPI <- function() {
stats <- GET("https://statsapi.web.nhl.com/api/v1/teams")

## As JSON text
stats <- content(stats, "text")

## As JSON List
stats <- fromJSON(stats, flatten = TRUE)
return(stats[[2]])
}
```

```{r}
teams <- TeamStatsAPI()
teams

```

```{r, Roster API}
RosterAPI <- function(id, ...) {
roster <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "/?expand=team.roster"))

## As JSON text
roster <- content(roster, "text")

## As JSON List
roster <- fromJSON(roster, flatten = TRUE)
franchiseId <- roster$teams$franchiseId
roster <- as_tibble(roster[[2]]$roster.roster[[1]]) %>% mutate("franchiseId" = franchiseId) %>% 
select(franchiseId, everything())
return(roster)
}
```

```{r, Person API}
PersonAPI <- function(id, ...) {
person <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "/?expand=person.names"))

## As JSON text
person <- content(person, "text")

## As JSON List
person <- fromJSON(person, flatten = TRUE)
return(person[[2]])
}
```

```{r, People API}
# Detailed substitue for PersonAPI
PeopleAPI <- function(id, ...) {
people <- GET(paste0("https://statsapi.web.nhl.com/api/v1/people/", id))

## As JSON text
people <- content(people, "text")

## As JSON List
people <- fromJSON(people, flatten = TRUE)
return(people[[2]])
}
```

```{r, team player}
## New DF combining People with Roster
TeamPlayer <- function (id, ...) {
playerId <- pull(RosterAPI(id), person.id)
players <- as.data.frame(PeopleAPI(playerId[1]))
  for (i in 2:length(playerId)) {
    players[i, ] <- (PeopleAPI(playerId[i]))
  }
players <- players %>% select(currentTeam.id, id, fullName, birthCountry, primaryPosition.name)
if(length(players$currentTeam.id) > 2) {
  players$currentTeam.id = players$currentTeam.id[[1]]
}
return(players) 
}
```

```{r, test team player}
TPtest <- TeamPlayer(12)
kable(head(TPtest), caption = "Player Stats")
```


```{r, Next Game API}
NextGAPI <- function(id, ...) {
nextG <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "?expand=team.schedule.next"))

## As JSON text
nextG <- content(nextG, "text")

## As JSON List
nextG <- fromJSON(nextG, flatten = TRUE)
nextG <- nextG[[2]]$nextGameSchedule.dates[[1]]$games[[1]]
return(nextG)
}
```

```{r, Prior Game API}
PriorGAPI <- function(id, ...) {
priorG <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "?expand=team.schedule.previous"))

## As JSON text
priorG <- content(priorG, "text")

## As JSON List
priorG <- fromJSON(priorG, flatten = TRUE)
priorG <- priorG[[2]]$previousGameSchedule.dates
return(priorG)
}
```


```{r, Expanded Stats API}
ExpStatsAPI <- function(id, ...) {
expStats <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "?expand=team.stats"))

## As JSON text
expStats <- content(expStats, "text")

## As JSON List
expStats <- fromJSON(expStats, flatten = TRUE)
expStats <- as.data.frame(expStats[[2]]$teamStats[[1]]$splits)
return(expStats)
}
```
```{r, expstas test}
expstatstest <- ExpStatsAPI(12)
expstatstest
```

```{r, Season Stats API}
SeasonAPI <- function(id, season, ...) {
season <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "?expand=team.roster&season=", season))

## As JSON text
season <- content(season, "text")

## As JSON List
season <- fromJSON(season, flatten = TRUE)
franchiseId <- season$teams$franchiseId
teamName <- season$teams$teamName
season <- as_tibble((season[[2]]$roster.roster[[1]])) %>% mutate("franchiseId" = franchiseId, "teamName" = teamName) %>% select(franchiseId, everything())
return(season)
}
```

```{r, Multi Teams API}
MultiAPI <- function(id, ...) {
multi <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", "?teamId=", id))

## As JSON text
multi <- content(multi, "text")

## As JSON List
multi <- fromJSON(multi, flatten = TRUE)
return(multi[[2]])
}
```

```{r, Playoffs API}
PlayoffAPI <- function(id, ...) {
playoff <- GET(paste0("https://statsapi.web.nhl.com/api/v1/teams/", id, "?stats=statsSingleSeasonPlayoffs"))

## As JSON text
playoff <- content(playoff, "text")

## As JSON List
playoff <- fromJSON(playoff, flatten = TRUE)
return(playoff[[2]])
}
```

## 2017 - 2019 Presidents Cup Teams vs. Low Points Teams Analysis

### Language

### Data

```{r, presidents, cache = TRUE}
# Roster for last 2 seasons, high points team (presidents cup) low points team
pres17 <- SeasonAPI(15, 20162017)
last17 <- SeasonAPI(21, 20162017)
pres18 <- SeasonAPI(18, 20172018)
last18 <- SeasonAPI(7, 20172018)
pres19 <- SeasonAPI(14, 20182019)
last19 <- SeasonAPI(9, 20182019)

# Combine results into single DS & add year & rank
PresLast <- bind_rows(pres17, last17, pres18, last18, pres19, last19)
PresLast <- mutate(PresLast, year = 
                  ifelse((PresLast$teamName == "Capitals") | (PresLast$teamName == "Avalanche"), 17,
                  ifelse((PresLast$teamName == "Predators") | (PresLast$teamName == "Sabres"), 18, 19)))
PresLast <- mutate(PresLast, rank = ifelse((PresLast$teamName == "Capitals") | (PresLast$teamName == "Predators") | (PresLast$teamName == "Lightning"), "First", "Last"))
PresLast <- PresLast %>% select(franchiseId, teamName, year, rank, person.id, person.fullName, jerseyNumber, position.code)

# Skater for detailed stats

# Franchise ID's for SkaterAPI argument

frIdList <- c(pres17$franchiseId[1], last17$franchiseId[1], pres18$franchiseId[1],last18$franchiseId[1], pres19$franchiseId[1], last19$franchiseId[1])

# Skater for detailed stats
PresLast_Skater <- lapply(frIdList, SkaterAPI)
PresLast_Skater <- bind_rows(PresLast_Skater)

# Combine results into single DS
PresLast_Skater <- PresLast_Skater %>% rename("person.id" = playerId) 

# Join Preslast & Preslast_Skater fo Skaters on Pres-last Teams / Seasons for analysis

PL_SK_Season <- inner_join(PresLast, PresLast_Skater) 
PL_SK_Season <-as_tibble(PL_SK_Season) %>% select(franchiseId, teamName, year, rank, person.id, person.fullName, jerseyNumber, position.code, seasons, penaltyMinutes, goals, assists, mostPointsOneSeason) %>% distinct()


PL_SK_Season <- PL_SK_Season %>% mutate(AveragePM = round((penaltyMinutes/seasons), 2), TotalPoints = (goals+assists), AverageTP = round((goals+assists)/seasons), 2)


QuantPM <- quantile(PL_SK_Season$AveragePM, probs = seq(0, 1, 1/3))
QuantTP <- quantile(PL_SK_Season$AverageTP, probs = seq(0, 1, 1/3))


PL_SK_Season <- mutate(PL_SK_Season, PMRank = 
                      ifelse((AveragePM <= 147) & (AveragePM > 26), "High 3rd",
                      ifelse((AveragePM <= 10), "Low 3rd", "Mid 3rd")),
                      TPRank = ifelse((AverageTP <= 85) & (AverageTP > 23), "High 3rd",
                      ifelse((AverageTP <= 6), "Low 3rd", "Mid 3rd")))      


PL_SK_Season <- PL_SK_Season %>% select(franchiseId, teamName, year, rank, person.fullName, position.code, seasons, AveragePM, PMRank, AverageTP, TPRank) %>% distinct()



PL_SK_Season <- PL_SK_Season %>% rename("Franchise ID" = franchiseId, "Team" = teamName, "Year" = year, "Finish" = rank, "Name" = person.fullName, "Position" = position.code, "Player Seasons" = seasons, "Avg Penalty Min" = AveragePM, "Penalty Min Rank" = PMRank, "Avg Total Pts" = AverageTP, "Total Pts Rank" = TPRank)

PL_SK_Season$Finish <- as.factor(PL_SK_Season$Finish)
PL_SK_Season$`Penalty Min Rank` <- as.factor(PL_SK_Season$`Penalty Min Rank`)
levels(PL_SK_Season$`Penalty Min Rank`) <- c("High PM", "Mid PM", "Low PM")
PL_SK_Season$`Total Pts Rank` <- as.factor(PL_SK_Season$`Total Pts Rank`)
levels(PL_SK_Season$`Total Pts Rank`) <- c( "High TP", "Mid TP", "Low TP")

kable(head(PL_SK_Season), n = 30, caption = "Preview of 2017 - 2019 Team Rosters: Presidents Cup vs Last Place")
```


```{r, Team Finish }
PMR_TPR_table <- table(PL_SK_Season$`Penalty Min Rank`, PL_SK_Season$`Total Pts Rank`)
kable(PMR_TPR_table, caption = "All Teams Penalty Min & Total Points Rank")
```

```{r, Pres PM_TP Rank}
PMR_TPR_F <- filter(PL_SK_Season, PL_SK_Season$Finish == "First")
PMR_TPR_F_table<- table(PMR_TPR_F$`Penalty Min Rank`, PMR_TPR_F$`Total Pts Rank`)
kable(PMR_TPR_F_table, caption = "Presidents Cup Winners")
```
```{r, Last PM_TP Rank}
PMR_TPR_L <- filter(PL_SK_Season, PL_SK_Season$Finish == "Last")
PMR_TPR_L_table<- table(PMR_TPR_L$`Penalty Min Rank`, PMR_TPR_L$`Total Pts Rank`)
kable(PMR_TPR_L_table, caption = "Last Place Teams")
```
## Visuals

### 1 Factor
```{r, univariate bar graphs}
# bar plot of Team Finish
FinPlot <- ggplot(PL_SK_Season, aes(x = Finish), color = "blue") 
FinPlot + geom_bar() + labs(x = "Team Finish")
```

### 2 Factors

```{r, 2 factor bar graphs}
# Finish by PM Rank
FxPMplot <- ggplot(PL_SK_Season, aes(Finish, fill = as.factor(`Penalty Min Rank`)))
FxPMplot + geom_bar(position = "dodge") +  scale_fill_discrete(name = "Penalty Minutes Rank") + labs(x = "Team Finish")

# Finish by TP Rank
FxTPplot <- ggplot(PL_SK_Season, aes(Finish, fill = as.factor(`Total Pts Rank`)))
FxTPplot + geom_bar(position = "dodge") +  scale_fill_discrete(name = "Total Points Rank") + labs(x = "Team Finish")
```

### 3 Factors
```{r, 3 factor bar graphs}
# Color by satellite indicator by spine condition
FxPMxPtplot <- ggplot(PL_SK_Season, aes(`Total Pts Rank`, fill = `Finish`))
FxPMxPtplot + geom_bar(position = "dodge") + scale_fill_discrete(name = "Team Finish") + labs(x = "Total Points", title = "Team Finish by Player Avg TP Rank & Player Avg PM Rank") + facet_wrap(. ~ `Penalty Min Rank`, labeller = (label_both))
```

```{r, player summaries}
# Function to knit 5 number sum + Mean given Species input
TeamSumm <- function(team, ...) {
summ <- PL_SK_Season %>% filter(Team == team) %>% select(c(7, 8, 10)) %>% apply(2, summary)
kable(summ, caption = paste0("Team: ", team))
}
```

```{r, TeamStats call }
teams <- (c("Capitals", "Avalanche", "Predators", "Sabres", "Lightning", "Senators"))

# Capitals summary
TeamSumm(teams[[1]])

# Avalanche summary
TeamSumm(teams[[2]])

# Predators summary
TeamSumm(teams[[3]])

# Sabres summary
TeamSumm(teams[[4]])

# lightning summary
TeamSumm(teams[[5]])

# Senators summary
TeamSumm(teams[[6]])

```


```{r, boxplot Avg TP}
# Base aesthetic wth Team on x & Avg Total Points on Y
Team <- PL_SK_Season$Team
Avg_Total_Points <- PL_SK_Season$`Avg Total Pts`
g <- ggplot(PL_SK_Season, aes(x = Team, y =Avg_Total_Points))

# Boxplot for Player Avg Total Point w Team overlay
g + geom_boxplot(fill = "white") + geom_jitter(aes(color = Team)) + labs(title = "Boxplot for Player's Career Avg Total Points")
```
```{r, boxplot Avg PM}
# Base aesthetic with Team on x & Avg Total Points on Y
Avg_Penalty_Min <- PL_SK_Season$`Avg Penalty Min`
g <- ggplot(PL_SK_Season, aes(x = Team, y =Avg_Penalty_Min))

# Boxplot for Player Average PM w/ Team overlay
g + geom_boxplot(fill = "white") + geom_jitter(aes(color = Finish)) + labs(title = "Boxplot for Player's Career Avg Penalty Minutes")
```

```{r, boxplot Years}
# Base aesthetic with Team on x & Player Years on Y
PLayer_Seasons <- PL_SK_Season$`Player Seasons`
g <- ggplot(PL_SK_Season, aes(x = Team, y = PLayer_Seasons))

# Boxplot for Player Seasons w/ Team overlay
g + geom_boxplot(fill = "white") + geom_jitter(aes(color = Finish)) + labs(title = "Boxplot for Player's Seasons in NHL")
```


```{r, dotplot by TotalPoints}
# Base plot aesthetic with Total Points on x axis
finish <- PL_SK_Season$Finish
g <- ggplot(PL_SK_Season, aes(x = Avg_Total_Points, y = PLayer_Seasons, color = Finish))

# Avg total points histogram
g + geom_point() + geom_smooth(aes(group = Team), method = lm, color = "blue") + labs(title =  "Players Average Total Points vs Seasons")
```

```{r, dotplot by Penalty Minutes}
# Base plot aesthetic with Total Points on x axis
g <- ggplot(PL_SK_Season, aes(x = Avg_Penalty_Min, y = PLayer_Seasons, color = Finish))

# Avg total points histogram
g + geom_point() + geom_smooth(aes(group = Team), method = lm, color = "blue") + labs(title =  "Players Average Total Points vs Seasons")
```

```{r, Test Stats API calls}
TeamStatsAPI_Call <- (TeamStatsAPI())
knitr::kable(TeamStatsAPI_Call)

RosterAPI_Call <- head(RosterAPI(10))
knitr::kable(RosterAPI_Call)

PersonAPI_Call <- head(PersonAPI(10))
knitr::kable(PersonAPI_Call)

PeopleAPI_Call <- head(PeopleAPI(8468508))
knitr::kable(PeopleAPI_Call)

NextGAPI_Call <- head(NextGAPI(1))
knitr::kable(NextGAPI_Call)

PriorGAPI_Call <- head(PriorGAPI(12))
knitr::kable(PriorGAPI_Call)

SeasonAPI_Call <- head(SeasonAPI(12, 20052006))
knitr::kable(SeasonAPI_Call)
```

